# SPDX-License-Identifier: Apache-2.0
#
# Copyright 2026 Gerald Venzl, Andres Almiray, Martin Bach
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Setup-Oracle-SQLcl

description: 'Setup Oracle SQLcl'

branding:
  icon: 'database'
  color: 'red'

inputs:
  version:
    description: 'The SQLcl version to download: latest or a fully qualified release like 25.4.2.044.1837'
    default: 'latest'
    required: true

  setup-java-version:
    default: '21'
    description: 'Setup internal Java runtime.'
    required: false

runs:
  using: 'composite'
  steps:
    - name: 'Setup Java'
      uses: actions/setup-java@v5
      if: ${{ inputs.setup-java-version != 'false' }}
      with:
        java-version: ${{ inputs.setup-java-version }}
        distribution: oracle

    - name: 'Verify Java Version'
      shell: bash
      run: "${GITHUB_ACTION_PATH}/verify_java.sh"

    - name: 'Setup SQLcl'
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
      run: "${GITHUB_ACTION_PATH}/setup_sqlcl.sh"
